version: '3.1'
services:
  flyway:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sleep 1d 
    volumes:
      - ${PWD}/sql_versions:/flyway/sql
      - ${PWD}/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - mysql 
    links:
      - mysql
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test-pass
      MYSQL_DATABASE: 'test-db'
    ports:
    - "3306:3306"
